### ISSUE TITLE
RuntimeError: Default process group has not been initialized

### ISSUE THREAD

**Issue by cleolotta** [microsoft/dp-transformers#6] opened 2022-08-18 09:03 UTC
Hi there, 
I'm trying to privatize a GPT-2 model with a dataset of my own. For that I'm using the fine-tune-dp.py script but with small adjustments regarding the dataset. 

    dataset = datasets.load_dataset("text", data_files=train_args.train_file)

    tokenizer = transformers.AutoTokenizer.from_pretrained(args.model.model_name)
    tokenizer.pad_token = -100 # Set a dummy pad token we don't use it anyway

    with train_args.main_process_first(desc="tokenizing dataset"):
        dataset = dataset.map(
            lambda batch: tokenizer(batch['text'], padding="max_length", truncation=True, max_length=args.model.sequence_len),
            batched=True, num_proc=8, desc="tokenizing dataset", remove_columns=dataset.column_names['train']
        )

I think this all works fine, however I get a RuntimeError which tells me that the default process group has not been initialized. 
Can someone tell me what to do? 

Thanks very much in advance! 

This is output of the script:

[INFO|configuration_utils.py:588]` 2022-08-18 10:18:22,287 >> loading configuration file https://huggingface.co/gpt2/resolve/main/config.json from cache at /.cache/huggingface/transformers/fc674cd6907b4c9e933cb42d67662436b89fa9540a1f40d7c919d0109289ad01.7d2e0efa5ca20cef4fb199382111e9d3ad96fd77b849e1d4bed13a66e1336f51
[INFO|configuration_utils.py:625] 2022-08-18 10:18:22,291 >> Model config GPT2Config {
  "activation_function": "gelu_new",
  "architectures": [
    "GPT2LMHeadModel"
  ],
  "attn_pdrop": 0.1,
  "bos_token_id": 50256,
  "embd_pdrop": 0.1,
  "eos_token_id": 50256,
  "initializer_range": 0.02,
  "layer_norm_epsilon": 1e-05,
  "model_type": "gpt2",
  "n_ctx": 1024,
  "n_embd": 768,
  "n_head": 12,
  "n_inner": null,
  "n_layer": 12,
  "n_positions": 1024,
  "reorder_and_upcast_attn": false,
  "resid_pdrop": 0.1,
  "scale_attn_by_inverse_layer_idx": false,
  "scale_attn_weights": true,
  "summary_activation": null,
  "summary_first_dropout": 0.1,
  "summary_proj_to_labels": true,
  "summary_type": "cls_index",
  "summary_use_proj": true,
  "task_specific_params": {
    "text-generation": {
      "do_sample": true,
      "max_length": 50
    }
  },
  "transformers_version": "4.12.2",
  "use_cache": true,
  "vocab_size": 50257
}

[INFO|modeling_utils.py:1340] 2022-08-18 10:18:23,257 >> loading weights file https://huggingface.co/gpt2/resolve/main/pytorch_model.bin from cache at /.cache/huggingface/transformers/752929ace039baa8ef70fe21cdf9ab9445773d20e733cf693d667982e210837e.323c769945a351daa25546176f8208b3004b6f563438a7603e7932bae9025925
[INFO|modeling_utils.py:1607] 2022-08-18 10:18:25,864 >> All model checkpoint weights were used when initializing GPT2LMHeadModel.

[INFO|modeling_utils.py:1615] 2022-08-18 10:18:25,866 >> All the weights of GPT2LMHeadModel were initialized from the model checkpoint at gpt2.
If your task is similar to the task the model of the checkpoint was trained on, you can already use GPT2LMHeadModel for predictions without further training.
100%|██████████| 1/1 [00:01<00:00,  1.15s/it]
[INFO|tokenization_auto.py:341] 2022-08-18 10:18:57,004 >> Could not locate the tokenizer configuration file, will try to use the model config instead.
[INFO|configuration_utils.py:588] 2022-08-18 10:18:57,431 >> loading configuration file https://huggingface.co/gpt2/resolve/main/config.json from cache at /.cache/huggingface/transformers/fc674cd6907b4c9e933cb42d67662436b89fa9540a1f40d7c919d0109289ad01.7d2e0efa5ca20cef4fb199382111e9d3ad96fd77b849e1d4bed13a66e1336f51
[INFO|configuration_utils.py:625] 2022-08-18 10:18:57,435 >> Model config GPT2Config {
  "activation_function": "gelu_new",
  "architectures": [
    "GPT2LMHeadModel"
  ],
  "attn_pdrop": 0.1,
  "bos_token_id": 50256,
  "embd_pdrop": 0.1,
  "eos_token_id": 50256,
  "initializer_range": 0.02,
  "layer_norm_epsilon": 1e-05,
  "model_type": "gpt2",
  "n_ctx": 1024,
  "n_embd": 768,
  "n_head": 12,
  "n_inner": null,
  "n_layer": 12,
  "n_positions": 1024,
  "reorder_and_upcast_attn": false,
  "resid_pdrop": 0.1,
  "scale_attn_by_inverse_layer_idx": false,
  "scale_attn_weights": true,
  "summary_activation": null,
  "summary_first_dropout": 0.1,
  "summary_proj_to_labels": true,
  "summary_type": "cls_index",
  "summary_use_proj": true,
  "task_specific_params": {
    "text-generation": {
      "do_sample": true,
      "max_length": 50
    }
  },
  "transformers_version": "4.12.2",
  "use_cache": true,
  "vocab_size": 50257
}

[INFO|tokenization_utils_base.py:1742] 2022-08-18 10:19:00,486 >> loading file https://huggingface.co/gpt2/resolve/main/vocab.json from cache at /.cache/huggingface/transformers/684fe667923972fb57f6b4dcb61a3c92763ad89882f3da5da9866baf14f2d60f.c7ed1f96aac49e745788faa77ba0a26a392643a50bb388b9c04ff469e555241f
[INFO|tokenization_utils_base.py:1742] 2022-08-18 10:19:00,488 >> loading file https://huggingface.co/gpt2/resolve/main/merges.txt from cache at /.cache/huggingface/transformers/c0c761a63004025aeadd530c4c27b860ec4ecbe8a00531233de21d865a402598.5d12962c5ee615a4c803841266e9c3be9a691a924f72d395d3a6c6c81157788b
[INFO|tokenization_utils_base.py:1742] 2022-08-18 10:19:00,490 >> loading file https://huggingface.co/gpt2/resolve/main/tokenizer.json from cache at /.cache/huggingface/transformers/16a2f78023c8dc511294f0c97b5e10fde3ef9889ad6d11ffaa2a00714e73926e.cf2d0ecb83b6df91b3dbb53f1d1e4c311578bfd3aa0e04934215a49bf9898df0
[INFO|tokenization_utils_base.py:1742] 2022-08-18 10:19:00,491 >> loading file https://huggingface.co/gpt2/resolve/main/added_tokens.json from cache at None
[INFO|tokenization_utils_base.py:1742] 2022-08-18 10:19:00,493 >> loading file https://huggingface.co/gpt2/resolve/main/special_tokens_map.json from cache at None
[INFO|tokenization_utils_base.py:1742] 2022-08-18 10:19:00,494 >> loading file https://huggingface.co/gpt2/resolve/main/tokenizer_config.json from cache at None
[INFO|configuration_utils.py:588] 2022-08-18 10:19:00,937 >> loading configuration file https://huggingface.co/gpt2/resolve/main/config.json from cache at /.cache/huggingface/transformers/fc674cd6907b4c9e933cb42d67662436b89fa9540a1f40d7c919d0109289ad01.7d2e0efa5ca20cef4fb199382111e9d3ad96fd77b849e1d4bed13a66e1336f51
[INFO|configuration_utils.py:625] 2022-08-18 10:19:00,941 >> Model config GPT2Config {
  "activation_function": "gelu_new",
  "architectures": [
    "GPT2LMHeadModel"
  ],
  "attn_pdrop": 0.1,
  "bos_token_id": 50256,
  "embd_pdrop": 0.1,
  "eos_token_id": 50256,
  "initializer_range": 0.02,
  "layer_norm_epsilon": 1e-05,
  "model_type": "gpt2",
  "n_ctx": 1024,
  "n_embd": 768,
  "n_head": 12,
  "n_inner": null,
  "n_layer": 12,
  "n_positions": 1024,
  "reorder_and_upcast_attn": false,
  "resid_pdrop": 0.1,
  "scale_attn_by_inverse_layer_idx": false,
  "scale_attn_weights": true,
  "summary_activation": null,
  "summary_first_dropout": 0.1,
  "summary_proj_to_labels": true,
  "summary_type": "cls_index",
  "summary_use_proj": true,
  "task_specific_params": {
    "text-generation": {
      "do_sample": true,
      "max_length": 50
    }
  },
  "transformers_version": "4.12.2",
  "use_cache": true,
  "vocab_size": 50257
}

tokenizing dataset #3: 100%|██████████| 456/456 [04:02<00:00,  1.88ba/s]
tokenizing dataset #4: 100%|██████████| 456/456 [04:07<00:00,  1.85ba/s]
tokenizing dataset #6: 100%|██████████| 456/456 [04:06<00:00,  1.85ba/s]
tokenizing dataset #5: 100%|██████████| 456/456 [04:07<00:00,  1.84ba/s]
tokenizing dataset #1: 100%|██████████| 456/456 [04:10<00:00,  1.82ba/s]
tokenizing dataset #7: 100%|██████████| 456/456 [04:10<00:00,  1.82ba/s]
tokenizing dataset #0: 100%|██████████| 456/456 [04:12<00:00,  1.80ba/s]
tokenizing dataset #2: 100%|██████████| 456/456 [04:12<00:00,  1.80ba/s]
Traceback (most recent call last):███▉| 451/456 [04:12<00:01,  4.01ba/s]
  File "/fplm/dp-transformers/fine-tune-dp.py", line 179, in <module>
    main(Arguments(train=train_args, privacy=privacy_args, model=model_args))
  File "/fplm/dp-transformers/fine-tune-dp.py", line 120, in main
    model = dp_transformers.dp_utils.DifferentiallyPrivateDistributedDataParallel(model)
  File "/fplm/miniconda3/env/lib/python3.9/site-packages/opacus/layers/dp_ddp.py", line 25, in __init__
    torch.distributed.broadcast(p.data, 0)
  File "/fplm/miniconda3/env/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 1075, in broadcast
    default_pg = _get_default_group()
  File "/fplm/miniconda3/env/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 358, in _get_default_group
    raise RuntimeError("Default process group has not been initialized, "
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.``

**Comment by amanoel** [comment] 2022-08-18 19:03
Hi @cleolotta, indeed a call to `init_process_group` is needed, but the `transformers` library does that for you typically, that's why we don't do it in our examples.

In particular if you look at e.g. `examples/nlg-reddit/sample-level-dp/fine-tune-dp.py`, we rely on the call to `parse_args_into_dataclasses` in line 172 which, ultimately, will result in `init_process_group` being called here `                torch.distributed.init_process_group(backend="nccl")`.
It's probably good practice in any case to do that before hand, so we might add that line also in our scripts.

In your case, invoking this line in the beginning of your script should suffice.
Please take a look here for more info: https://pytorch.org/tutorials/intermediate/ddp_tutorial.html#initialize-ddp-with-torch-distributed-run-torchrun

**Comment by amanoel** [comment] 2022-08-18 19:17
p.s.: also, for now, we assume you are launching the code using `python -m torch.distributed.run` or `torchrun`. If you launch it just as `python fine-tune.dp.py`, it won't work, and you'll get this exact message.

Even if you have only 1 GPU, you can do `python -m torch.distributed.run --nproc_per_node 1`, that should fix it for now. We will prepare a version of it that can be used in 1 GPU without DPDDP.

**Comment by cleolotta** [comment] 2022-08-24 21:07
Thank you @amanoel! I tried it again with commenting out `model = dp_transformers.dp_utils.DifferentiallyPrivateDistributedDataParallel(model) ` and also with `python -m torch.distributed.run --nproc_per_node 1`. 

This is how I run it: python -m torch.distributed.run --nproc_per_node 1 /fplm/dp-transformers/fine-tune-dp.py --output_dir=/fplm/dp-transformers/dp_gpt2 --model_name gpt2-medium --sequence_len 128 --per_device_train_batch_size 64 --gradient_accumulation_steps 1 --evaluation_strategy steps --eval_steps 45 --log_level info --per_device_eval_batch_size 64 --eval_accumulation_steps 1 --seed 42 --target_epsilon 8 --per_sample_max_grad_norm 1.0 --prediction_loss_only --weight_decay 0.01 --remove_unused_columns False --num_train_epochs 3 --logging_steps 5 --lora_dim 4 --lora_alpha 32 --lora_dropout 0.0 --max_grad_norm 0 --lr_scheduler_type constant --learning_rate 3e-5 --disable_tqdm True --dataloader_num_workers 2

However, I get the following error:

[INFO|configuration_utils.py:684] 2022-08-24 19:36:06,683 >> Model config GPT2Config {
  "_name_or_path": "gpt2-medium",
  "activation_function": "gelu_new",
  "architectures": [
    "GPT2LMHeadModel"
  ],
  "attn_pdrop": 0.1,
  "bos_token_id": 50256,
  "embd_pdrop": 0.1,
  "eos_token_id": 50256,
  "initializer_range": 0.02,
  "layer_norm_epsilon": 1e-05,
  "model_type": "gpt2",
  "n_ctx": 1024,
  "n_embd": 1024,
  "n_head": 16,
  "n_inner": null,
  "n_layer": 24,
  "n_positions": 1024,
  "n_special": 0,
  "predict_special_tokens": true,
  "reorder_and_upcast_attn": false,
  "resid_pdrop": 0.1,
  "scale_attn_by_inverse_layer_idx": false,
  "scale_attn_weights": true,
  "summary_activation": null,
  "summary_first_dropout": 0.1,
  "summary_proj_to_labels": true,
  "summary_type": "cls_index",
  "summary_use_proj": true,
  "task_specific_params": {
    "text-generation": {
      "do_sample": true,
      "max_length": 50
    }
  },
  "transformers_version": "4.17.0",
  "use_cache": true,
  "vocab_size": 50257
}

 /fplm/miniconda3/env/lib/python3.9/site-packages/dp_transformers/module_modification.py:19: UserWarning: It looks like you have a model with a classification or LM head. If this is the case, pass `model.transformer` to `convert_gpt2_attention_to_lora` to avoid this warning.
  warnings.warn("""It looks like you have a model with a classification or LM head. """
 /fplm/miniconda3/env/lib/python3.9/site-packages/opacus/privacy_engine.py:752: UserWarning: The sample rate will be defined from ``batch_size`` and ``sample_size``.The returned privacy budget will be incorrect.
  warnings.warn(
 /fplm/miniconda3/env/lib/python3.9/site-packages/opacus/privacy_engine.py:236: UserWarning: Secure RNG turned off. This is perfectly fine for experimentation as it allows for much faster training performance, but remember to turn it on and retrain one last time before production with ``secure_rng`` turned on.
  warnings.warn(
 /fplm/miniconda3/env/lib/python3.9/site-packages/transformers/optimization.py:306: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
[INFO|trainer.py:1254] 2022-08-24 19:46:16,175 >> ***** Running training *****
[INFO|trainer.py:1255] 2022-08-24 19:46:16,176 >>   Num examples = 3647844
[INFO|trainer.py:1256] 2022-08-24 19:46:16,178 >>   Num Epochs = 3
[INFO|trainer.py:1257] 2022-08-24 19:46:16,180 >>   Instantaneous batch size per device = 64
[INFO|trainer.py:1258] 2022-08-24 19:46:16,181 >>   Total train batch size (w. parallel, distributed & accumulation) = 64
[INFO|trainer.py:1259] 2022-08-24 19:46:16,183 >>   Gradient Accumulation steps = 1
[INFO|trainer.py:1260] 2022-08-24 19:46:16,185 >>   Total optimization steps = 170991
 /fplm/miniconda3/env/lib/python3.9/site-packages/torch/nn/modules/module.py:974: UserWarning: Using a non-full backward hook when the forward contains multiple autograd Nodes is deprecated and will be removed in future versions. This hook will be missing some grad_input. Please use register_full_backward_hook to get the documented behavior.
  warnings.warn("Using a non-full backward hook when the forward contains multiple autograd Nodes "
[W reducer.cpp:1158] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
Traceback (most recent call last):
  File " /fplm/dp-transformers/fine-tune-dp.py", line 179, in <module>
    main(Arguments(train=train_args, privacy=privacy_args, model=model_args))
  File " /fplm/dp-transformers/fine-tune-dp.py", line 167, in main
    trainer.train()
  File " /fplm/miniconda3/env/lib/python3.9/site-packages/transformers/trainer.py", line 1375, in train
    tr_loss_step = self.training_step(model, inputs)
  File " /fplm/miniconda3/env/lib/python3.9/site-packages/dp_transformers/dp_utils.py", line 229, in training_step
    loss.backward()
  File " /fplm/miniconda3/env/lib/python3.9/site-packages/torch/_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File " /fplm/miniconda3/env/lib/python3.9/site-packages/torch/autograd/__init__.py", line 147, in backward
    Variable._execution_engine.run_backward(
RuntimeError: CUDA out of memory. Tried to allocate 1.52 GiB (GPU 0; 31.75 GiB total capacity; 27.68 GiB already allocated; 237.44 MiB free; 30.07 GiB reserved in total by PyTorch)
[ERROR] 2022-08-24 19:46:23,296 api: failed (exitcode: 1) local_rank: 0 (pid: 93461) of binary:  /fplm/miniconda3/env/bin/python
[ERROR] 2022-08-24 19:46:23,298 local_elastic_agent: [default] Worker group failed
[INFO] 2022-08-24 19:46:23,300 api: [default] Worker group FAILED. 3/3 attempts left; will restart worker group
[INFO] 2022-08-24 19:46:23,302 api: [default] Stopping worker group
[INFO] 2022-08-24 19:46:23,304 api: [default] Rendezvous'ing worker group
[INFO] 2022-08-24 19:46:23,305 static_tcp_rendezvous: Creating TCPStore as the c10d::Store implementation
[INFO] 2022-08-24 19:46:23,308 api: [default] Rendezvous complete for workers. Result:
  restart_count=1
  master_addr=127.0.0.1
  master_port=29500
  group_rank=0
  group_world_size=1
  local_ranks=[0]
  role_ranks=[0]
  global_ranks=[0]
  role_world_sizes=[1]
  global_world_sizes=[1]

[INFO] 2022-08-24 19:46:23,310 api: [default] Starting worker group
[INFO] 2022-08-24 19:46:23,313 __init__: Setting worker0 reply file to: /scratch/19097/torchelastic_7xi797u_/none_1aygsf2m/attempt_1/0/error.json
Traceback (most recent call last):
  File " /fplm/dp-transformers/fine-tune-dp.py", line 178, in <module>
    train_args, privacy_args, model_args = arg_parser.parse_args_into_dataclasses()
  File " /fplm/miniconda3/env/lib/python3.9/site-packages/transformers/hf_argparser.py", line 206, in parse_args_into_dataclasses
    obj = dtype(**inputs)
  File "<string>", line 90, in __init__
  File " /fplm/miniconda3/env/lib/python3.9/site-packages/dp_transformers/arguments.py", line 47, in __post_init__
    super().__post_init__()
  File " /fplm/miniconda3/env/lib/python3.9/site-packages/transformers/training_args.py", line 851, in __post_init__
    and (self.device.type != "cuda")
  File " /fplm/miniconda3/env/lib/python3.9/site-packages/transformers/file_utils.py", line 2477, in wrapper
    return func(*args, **kwargs)
  File " /fplm/miniconda3/env/lib/python3.9/site-packages/transformers/training_args.py", line 1079, in device
    return self._setup_devices
  File " /fplm/miniconda3/env/lib/python3.9/site-packages/transformers/file_utils.py", line 2467, in __get__
    cached = self.fget(obj)
  File " /fplm/miniconda3/env/lib/python3.9/site-packages/transformers/file_utils.py", line 2477, in wrapper
    return func(*args, **kwargs)
  File " /fplm/miniconda3/env/lib/python3.9/site-packages/transformers/training_args.py", line 1064, in _setup_devices
    torch.distributed.init_process_group(backend="nccl")
  File " /fplm/miniconda3/env/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 547, in init_process_group
    _store_based_barrier(rank, store, timeout)
  File " /fplm/miniconda3/env/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 219, in _store_based_barrier
    raise RuntimeError(
RuntimeError: Timed out initializing process group in store based barrier on rank: 0, for key: store_based_barrier_key:1 (world_size=1, worker_count=2, timeout=0:30:00)
[ERROR] 2022-08-24 20:16:45,037 api: failed (exitcode: 1) local_rank: 0 (pid: 94302) of binary:  /fplm/miniconda3/env/bin/python
[ERROR] 2022-08-24 20:16:45,039 local_elastic_agent: [default] Worker group failed
[INFO] 2022-08-24 20:16:45,041 api: [default] Worker group FAILED. 2/3 attempts left; will restart worker group
[INFO] 2022-08-24 20:16:45,042 api: [default] Stopping worker group
[INFO] 2022-08-24 20:16:45,044 api: [default] Rendezvous'ing worker group
[INFO] 2022-08-24 20:16:45,046 static_tcp_rendezvous: Creating TCPStore as the c10d::Store implementation
[INFO] 2022-08-24 20:16:45,049 api: [default] Rendezvous complete for workers. Result:
  restart_count=2
  master_addr=127.0.0.1
  master_port=29500
  group_rank=0
  group_world_size=1
  local_ranks=[0]
  role_ranks=[0]
  global_ranks=[0]
  role_world_sizes=[1]
  global_world_sizes=[1]

[INFO] 2022-08-24 20:16:45,050 api: [default] Starting worker group
[INFO] 2022-08-24 20:16:45,053 __init__: Setting worker0 reply file to: /scratch/19097/torchelastic_7xi797u_/none_1aygsf2m/attempt_2/0/error.json
Traceback (most recent call last):
  File " /fplm/dp-transformers/fine-tune-dp.py", line 178, in <module>
    train_args, privacy_args, model_args = arg_parser.parse_args_into_dataclasses()
  File " /fplm/miniconda3/env/lib/python3.9/site-packages/transformers/hf_argparser.py", line 206, in parse_args_into_dataclasses
    obj = dtype(**inputs)
  File "<string>", line 90, in __init__
  File " /fplm/miniconda3/env/lib/python3.9/site-packages/dp_transformers/arguments.py", line 47, in __post_init__
    super().__post_init__()
  File " /fplm/miniconda3/env/lib/python3.9/site-packages/transformers/training_args.py", line 851, in __post_init__
    and (self.device.type != "cuda")
  File " /fplm/miniconda3/env/lib/python3.9/site-packages/transformers/file_utils.py", line 2477, in wrapper
    return func(*args, **kwargs)
  File " /fplm/miniconda3/env/lib/python3.9/site-packages/transformers/training_args.py", line 1079, in device
    return self._setup_devices
  File " /fplm/miniconda3/env/lib/python3.9/site-packages/transformers/file_utils.py", line 2467, in __get__
    cached = self.fget(obj)
  File " /fplm/miniconda3/env/lib/python3.9/site-packages/transformers/file_utils.py", line 2477, in wrapper
    return func(*args, **kwargs)
  File " /fplm/miniconda3/env/lib/python3.9/site-packages/transformers/training_args.py", line 1064, in _setup_devices
    torch.distributed.init_process_group(backend="nccl")
  File " /fplm/miniconda3/env/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 547, in init_process_group
    _store_based_barrier(rank, store, timeout)
  File " /fplm/miniconda3/env/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 219, in _store_based_barrier
    raise RuntimeError(
RuntimeError: Timed out initializing process group in store based barrier on rank: 0, for key: store_based_barrier_key:1 (world_size=1, worker_count=3, timeout=0:30:00)
[ERROR] 2022-08-24 20:47:06,794 api: failed (exitcode: 1) local_rank: 0 (pid: 95260) of binary:  /fplm/miniconda3/env/bin/python
[ERROR] 2022-08-24 20:47:06,797 local_elastic_agent: [default] Worker group failed
[INFO] 2022-08-24 20:47:06,799 api: [default] Worker group FAILED. 1/3 attempts left; will restart worker group
[INFO] 2022-08-24 20:47:06,800 api: [default] Stopping worker group
[INFO] 2022-08-24 20:47:06,802 api: [default] Rendezvous'ing worker group
[INFO] 2022-08-24 20:47:06,804 static_tcp_rendezvous: Creating TCPStore as the c10d::Store implementation
[INFO] 2022-08-24 20:47:06,807 api: [default] Rendezvous complete for workers. Result:
  restart_count=3
  master_addr=127.0.0.1
  master_port=29500
  group_rank=0
  group_world_size=1
  local_ranks=[0]
  role_ranks=[0]
  global_ranks=[0]
  role_world_sizes=[1]
  global_world_sizes=[1]

[INFO] 2022-08-24 20:47:06,809 api: [default] Starting worker group
[INFO] 2022-08-24 20:47:06,812 __init__: Setting worker0 reply file to: /scratch/19097/torchelastic_7xi797u_/none_1aygsf2m/attempt_3/0/error.json
Traceback (most recent call last):
  File " /fplm/dp-transformers/fine-tune-dp.py", line 178, in <module>
    train_args, privacy_args, model_args = arg_parser.parse_args_into_dataclasses()
  File " /fplm/miniconda3/env/lib/python3.9/site-packages/transformers/hf_argparser.py", line 206, in parse_args_into_dataclasses
    obj = dtype(**inputs)
  File "<string>", line 90, in __init__
  File " /fplm/miniconda3/env/lib/python3.9/site-packages/dp_transformers/arguments.py", line 47, in __post_init__
    super().__post_init__()
  File " /fplm/miniconda3/env/lib/python3.9/site-packages/transformers/training_args.py", line 851, in __post_init__
    and (self.device.type != "cuda")
  File " /fplm/miniconda3/env/lib/python3.9/site-packages/transformers/file_utils.py", line 2477, in wrapper
    return func(*args, **kwargs)
  File " /fplm/miniconda3/env/lib/python3.9/site-packages/transformers/training_args.py", line 1079, in device
    return self._setup_devices
  File " /fplm/miniconda3/env/lib/python3.9/site-packages/transformers/file_utils.py", line 2467, in __get__
    cached = self.fget(obj)
  File " /fplm/miniconda3/env/lib/python3.9/site-packages/transformers/file_utils.py", line 2477, in wrapper
    return func(*args, **kwargs)
  File " /fplm/miniconda3/env/lib/python3.9/site-packages/transformers/training_args.py", line 1064, in _setup_devices
    torch.distributed.init_process_group(backend="nccl")
  File " /fplm/miniconda3/env/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 547, in init_process_group
    _store_based_barrier(rank, store, timeout)
  File " /fplm/miniconda3/env/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 219, in _store_based_barrier
    raise RuntimeError(
RuntimeError: Timed out initializing process group in store based barrier on rank: 0, for key: store_based_barrier_key:1 (world_size=1, worker_count=4, timeout=0:30:00)
[ERROR] 2022-08-24 21:17:28,580 api: failed (exitcode: 1) local_rank: 0 (pid: 96270) of binary:  /fplm/miniconda3/env/bin/python
[ERROR] 2022-08-24 21:17:28,582 local_elastic_agent: [default] Worker group failed
[INFO] 2022-08-24 21:17:28,584 api: Local worker group finished (FAILED). Waiting 300 seconds for other agents to finish
 /fplm/miniconda3/env/lib/python3.9/site-packages/torch/distributed/elastic/utils/store.py:70: FutureWarning: This is an experimental API and will be changed in future.
  warnings.warn(
[INFO] 2022-08-24 21:17:28,588 api: Done waiting for other agents. Elapsed: 0.002313852310180664 seconds
{"name": "torchelastic.worker.status.FAILED", "source": "WORKER", "timestamp": 0, "metadata": {"run_id": "none", "global_rank": 0, "group_rank": 0, "worker_id": "96270", "role": "default", "hostname": "melvin.ukp.informatik.tu-darmstadt.de", "state": "FAILED", "total_run_time": 6141, "rdzv_backend": "static", "raw_error": "{\"message\": \"<NONE>\"}", "metadata": "{\"group_world_size\": 1, \"entry_point\": \"python\", \"local_rank\": [0], \"role_rank\": [0], \"role_world_size\": [1]}", "agent_restarts": 3}}
{"name": "torchelastic.worker.status.SUCCEEDED", "source": "AGENT", "timestamp": 0, "metadata": {"run_id": "none", "global_rank": null, "group_rank": 0, "worker_id": null, "role": "default", "hostname": "melvin.ukp.informatik.tu-darmstadt.de", "state": "SUCCEEDED", "total_run_time": 6141, "rdzv_backend": "static", "raw_error": null, "metadata": "{\"group_world_size\": 1, \"entry_point\": \"python\"}", "agent_restarts": 3}}
 /fplm/miniconda3/env/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py:354: UserWarning:

**********************************************************************
               CHILD PROCESS FAILED WITH NO ERROR_FILE
**********************************************************************
CHILD PROCESS FAILED WITH NO ERROR_FILE
Child process 96270 (local_rank 0) FAILED (exitcode 1)
Error msg: Process failed with exitcode 1
Without writing an error file to <N/A>.
While this DOES NOT affect the correctness of your application,
no trace information about the error will be available for inspection.
Consider decorating your top level entrypoint function with
torch.distributed.elastic.multiprocessing.errors.record. Example:

  from torch.distributed.elastic.multiprocessing.errors import record

  @record
  def trainer_main(args):
     # do train
**********************************************************************
  warnings.warn(_no_error_file_warning_msg(rank, failure))
Traceback (most recent call last):
  File " /fplm/miniconda3/env/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File " /fplm/miniconda3/env/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File " /fplm/miniconda3/env/lib/python3.9/site-packages/torch/distributed/run.py", line 637, in <module>
    main()
  File " /fplm/miniconda3/env/lib/python3.9/site-packages/torch/distributed/run.py", line 629, in main
    run(args)
  File " /fplm/miniconda3/env/lib/python3.9/site-packages/torch/distributed/run.py", line 621, in run
    elastic_launch(
  File " /fplm/miniconda3/env/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 116, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File " /fplm/miniconda3/env/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 348, in wrapper
    return f(*args, **kwargs)
  File " /fplm/miniconda3/env/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
*************************************************************************
   /fplm/dp-transformers/fine-tune-dp.py FAILED
=========================================================================
Root Cause:
[0]:
  time: 2022-08-24_21:17:28
  rank: 0 (local_rank: 0)
  exitcode: 1 (pid: 96270)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
=========================================================================
Other Failures:
  <NO_OTHER_FAILURES>
*************************************************************************

**Comment by amanoel** [comment] 2022-08-25 14:00
Seems it's a OOM:

> RuntimeError: CUDA out of memory. Tried to allocate 1.52 GiB (GPU 0; 31.75 GiB total capacity; 27.68 GiB already allocated; 237.44 MiB free; 30.07 GiB reserved in total by PyTorch)

If you can't find machines with more than 1 GPU, you might have to reduce your batch size!

**Comment by amanoel** [comment] 2022-08-25 14:03
I'll close this since root cause of the original issue has been identified and fixed in #8. Please feel free to open another issue if needed.

**Closed by amanoel** 2022-08-25 14:03 UTC

**Comment by huseyinatahaninan** [comment] 2022-08-25 21:58
Hi @cleolotta, DP training in general requires more memory so you'd need to reduce  `--per_device_train_batch_size 64` to a value where it starts to fit into your GPU memory. On the other hand, DP training performance is highly dependent on using large batch sizes and the way you can achieve that is by using `--gradient_accumulation_steps` basically. Based on your dataset size, I'd say you can increase the effective batch size to 1k-10k, perhaps even more and then if you train for longer it will also get better. Though it'll also take a longer training time to do that.

Since you have a single GPU, I don't know the memory of it but probably you can try first `--per_device_train_batch_size 8` and `--gradient_accumulation_steps 128` and then based on how much training time you can afford, you can increase the effective batch size (--per_device_train_batch_size * --gradient_accumulation_steps * # of GPUs) even more and train longer to get better and better performance. When you have memory errors, reduce `--per_device_train_batch_size` and compensate it with `--gradient_accumulation_steps`.

I hope this helps..
